# Example: show the weather on the right of the status bar.

set -g @plugin 'gufranco/tmux-weather-revamped'

set -g @tmux-weather-location 'Sao Paulo'
set -g @tmux-weather-units 'm'
set -g @tmux-weather-interval '15'

set -g status-right '#{weather} '
